name = "Grey Hill"
location = "Victoria, BC, Canada"
email = "infogreytech@gmail.com"

[[accounts]]
site = "GitHub"
username = "greyhillman"
link = "https://github.com/greyhillman"

[[accounts]]
site = "LinkedIn"
username = "greyhillman"
link = "https://www.linkedin.com/in/greyhillman"

#
# JOBS
#

#
# XPLOR RECREATION
#

[[jobs]]
company = "Xplor Recreation"

[[jobs.positions]]
title = "Intermediate Software Developer"
location = "remote"
start = 2023-05-01
end = 2024-06-15
skills = [
    "Lead project on migrating $100k/month production AWS to Terraform",
    "Maintained $100k/month AWS accounts",
    "Managed and developed 50+ Bamboo plans and deployments",
    "Fixed issue with Debug builds being deployed to production",
    "Acted as an unofficial Team Lead when needed by teammates",                 # Edward agreed with my assessment
    "Conducted exit interview when management failed to arrange it",
    "Launched and monitored 20+ ECS services",
    "Launched and monitored 5+ AWS Lambda functions",
    "Replaced bespoke Packer and Bamboo builds for AMIs with AWS Image Builder",
    "Trained co-op on software development basics",                              # George
]
knowledge.high = [
    "Terraform",
    "Bamboo",
    "AWS",
    "AWS ECS",
    "AWS Lambda",
    "AWS S3",
    "AWS EC2",
]
knowledge.medium = [
    "Dhall",
    "AWS CloudFront",
    "AWS IAM",
    "AWS Image Builder",
    "AWS ELB",
]

[[jobs.positions.quotes]]
quote = "Your presence, knowledge, and will to help will be missed!"
name = "Marcio"
position = "Site Reliability Engineer"
relation = "Co-worker"

[[jobs.positions.quotes]]
quote = "Can you leave your brain with us?"
name = "Marcio"
position = "Site Reliability Engineer"
relation = "Co-worker"

[[jobs.positions.quotes]]
quote = "You have the courage to say what others want to say but cannot"
name = "Unknown"
position = "Engineering"
relation = "Co-worker"

[[jobs.positions.quotes]]
quote = "You have been instrumental in so many projects."
name = "Kia"
position = "Director of Product"
relation = "Management"

[[jobs.positions.quotes]]
quote = "... you helped provide direction, and I always appreciated you sharing your knowledge while troubleshooting."
name = "Edward"
position = "Software Developer"
relation = "Co-worker"

[[jobs.positions]]
title = "Junior Software Developer"
start = 2022-04-01
end = 2023-05-01
location = "remote"
skills = [
    "Identified $35k/year in AWS savings for ECS clusters",
    "Migrated internal tool's AWS infrastructure to Terraform",
    "Designed, built, and maintained distributed SQL Server script runner in C#",
    "Maintained ASP.NET MVC internal management tool used by 20+ daily users",
    "Eliminated EC2 instance cycling due to incorrect auto-scaling policies",
    "Trained co-op on software development basics",                               # Edward
    "Planned migration of 50+ Bamboo builds and deployments to Bamboo Specs",
    "Used Dhall for Bamboo Specs to reduce repetition",
    "Learned AWS via Udemy and applied learning immediately",
    "Aligned internal tool styling to follow company's style guide",
]
knowledge.high = ["C#", "AWS", "AWS ECS", "AWS Lambda", "ASP.NET MVC"]
knowledge.medium = [
    "HTML",
    "SCSS",
    "Jira",
    "AWS DynamoDB",
    "AWS SQS",
    "AWS ELB",
]

#
# HELM OPERATIONS
#

[[jobs]]
company = "Helm Operations"

[[jobs.positions]]
title = "Full-stack Developer"
start = 2019-04-01
end = 2021-07-01
location = "hybrid"
skills = [
    "Continual advocate for best practises across code, UI/UX, processes",
    "Fixed several core issues within first year to recover system from major outage",
    "Cut DB usage by ~50% by fixing core issue during major outage",
    "Used property-based testing to improve confidence in payroll system refactoring",
    "Designed and built server-side data generators for load testing",
]
knowledge.high = [
    "C#",
    "SQL Server",
    "KnockoutJS",
    "Visual Studio",
    "VSCode",
    "git",
    "Jira",
]
knowledge.medium = [
    "JavaScript",
    "HTML",
    "CSS",
    "LessCSS",
    ".NET Framework",
    "NUnit",
    "Confluence",
]
knowledge.low = ["PostgreSQL", "PowerShell"]

[[jobs.positions.quotes]]
quote = "We're definitely going to miss your humour and attention to quality and detail"
name = "Kathy"
position = "Technical Writer"
relation = "Coworker"

[[jobs.positions.quotes]]
quote = "I'm gonna miss your attention to all the high-level problems in our code"
name = "Tim"
position = "Full-stack Developer"
relation = "Coworker"

[[jobs.positions.quotes]]
quote = "Talented dev with well-thought-out solutions and attention to good coding practices"
name = "Peter"
position = "Team Lead"
relation = "Boss"

[[jobs.positions]]
title = "Software Developer"
start = 2019-01-01
end = 2019-04-01
contract = "co-op"
location = "on-site"
knowledge.high = ["C#", "KnockoutJS", "VSCode"]
knowledge.medium = [
    "JavaScript",
    "HTML",
    "LessCSS",
    "CSS",
    "SQL Server",
    "Visual Studio",
]
knowledge.low = [".NET Framework", "Jira", "Confluence"]

#
# LATITUDE GEOGRAPHICS
#

[[jobs]]
company = "Latitude Geographics"

[[jobs.positions]]
title = "Quality Assurance Analyst"
contract = "co-op"
start = 2018-05-01
end = 2018-08-31
location = "on-site"
skills = [
    "Gave recommendations on design of end-to-end tests (\"model\"-based)",
    "Introduced tool to improve QA reports",
    "Developed TypeScript automated end-to-end tests for new product",
]
knowledge.high = ["TypeScript", "WebDriverIO", "VSCode"]

#
# UVIC CIVIL ENGINEERING
#

[[jobs]]
company = "UVic Civil Engineering"

[[jobs.positions]]
title = "Software Developer"
contract = "co-op"
start = 2017-05-01
end = 2017-08-31
location = "on-site"
skills = [
    "Refactored researcher's code to allow for future development (also fixed critical issue)",
    "Explained technical concepts to non-technical people",
]
knowledge.high = ["Python 3", "VSCode"]
knowledge.low = ["Docker"]

[[jobs.positions.quotes]]
quote = "Good at explaining technical concepts to non-technical people"
name = "Ralph"
position = "Professor/Head Researcher"
relation = "Boss"

#
# DEMONWARE
#

[[jobs]]
company = "Demonware"

[[jobs.positions]]
title = "Software Developer"
contract = "co-op"
start = 2016-09-01
end = 2016-12-31
location = "on-site"
skills = [
    "Learned basics of software development",
    "Participated in Agile development processes",
]
knowledge.high = ["Python 2", "git"]
knowledge.low = ["Agile", "Scrum"]

#
# PROJECTS
#

[[projects]]
title = "Lamport Clock Paper"
purpose = "To create an interactive paper; to deeply understand Lamport Clocks"
link = "https://greyhillman.github.io/lamport-clock-paper/"
repo = "https://github.com/greyhillman/lamport-clock-paper"
start_date = 2024-12-23
skills = [
    "Used Web Components via Lit for future reusability",
    "Created animated visualizations using SVG",
    "Created interactive simulations using KonvaJS",
]
knowledge.high = [
    "HTML",
    "CSS",
    "TypeScript",
    "Preact",
    "Lit",
    "KonvaJS",
    "Web Components",
]

[[projects]]
title = "Apartment Noise Tracker"
purpose = "To learn basics of creating a Progressive Web App; to help me file noise complaints"
link = "https://greyhillman.github.io/apartment-noise-tracker"
repo = "https://github.com/greyhillman/apartment-noise-tracker"
start_date = 2024-11-14
end_date = 2024-12-09
skills = [
    "Allowed offline use by making it a Progressive Web App (PWA)",
    "Used modern CSS for responsive design (mobile/desktop & dark/light mode)",
    "Created Playwright tests to allow CSS refactoring",
]
knowledge.high = ["SolidJS", "CSS", "TypeScript", "PWA"]
knowledge.medium = ["Vite", "Playwright"]

[[projects]]
title = "Personal Blog"
link = "https://greyhillman.github.io"
repo = "https://github.com/greyhillman/greyhillman.github.io"
purpose = "To explain my ideas; teach others via explorable explanations"

[[projects]]
title = "Rent vs. Buy Calculator"
purpose = "To help make an important decision & convince others"
link = "https://greyhillman.github.io/rent-vs-buy/"
repo = "https://github.com/greyhillman/rent-vs-buy"
start_date = 2021-08-10
end_date = 2021-09-09
skills = ["Learned React (with hooks) to build frontend"]
knowledge.high = ["React", "TypeScript"]

[[projects]]
title = "Resume"
purpose = "To hold all resume data; change resume quickly & easily"
link = "https://greyhillman.github.io/Resume/"
repo = "https://github.com/greyhillman/Resume"
start_date = 2021-11-30
skills = [
    "Used Dhall to hold data & configure content",
    "Refactored from Dhall to TOML to shorten feedback loop",
    "Created GitHub pages workflow for human capital",
]
knowledge.high = ["TOML", "HTML", "CSS", "C#"]

[[projects]]
title = "Personal Finance System"
purpose = "To track finances; automatically produce financial reports"
start_date = 2019-06-22
skills = [
    "Used Haskell's Shake build system to generate reports",
    "Migrated to .NET due to limitations in hledger",
    "Created new accounting Nuget packages based on hledger",
    "Created new build system in .NET based on Haskell's Shake library",
    "Maintaining 7+ years of financial data with monthly additions",
]
knowledge.high = ["Dhall", "C#", ".NET 7"]

[[projects]]
title = "ECS-EC2 Simulator"
purpose = "To debug turbulent ECS & EC2 scaling"
link = "https://greyhillman.github.io/simulators/ecs-ec2/index.html"
repo = "https://github.com/greyhillman/greyhillman.github.io/tree/master/site/simulators/ecs-ec2"
start_date = 2023-03-22
end_date = 2023-04-22
skills = [
    "Created simulation of AWS Auto-scaling groups",
    "Created simulation of ECS auto-scaling",
]
knowledge.high = ["AWS ECS", "AWS ASG", "Vue"]

#
# DEGREES
#

[[degrees]]
title = "Bachelor of Science (Honours) (Co-op)"
faculty = "Computer Science"
university = "University of Victoria"
start = 2014-09-01
end = 2019-04-30
skills = ["GPA: 8.5/9"]

#
# CERTIFICATIONS
#

[[certifications]]
name = "AWS Certified Solutions Architect - Associate"
organization = "Amazon Web Services (AWS)"
valid_start = 2023-10-27
valid_end = 2026-10-27
url = "https://www.credly.com/badges/6d92b1c5-e35f-411f-90b0-18eed1fb7d04/linked_in_profile"

#
# SCHOLARSHIPS
#

[[scholarships]]
name = "UVic Entrance Scholarship"
institution = "University of Victoria"
date = 2014
amount = 3000

[[scholarships]]
name = "Dean's Entrance Scholarship"
institution = "University of Victoria"
date = 2014
amount = 1000

[[scholarships]]
name = "President's Scholarship"
institution = "University of Victoria"
date = 2015
amount = 3750

[[scholarships]]
name = "James Riddell Memorial Scholarship"
institution = "University of Victoria"
date = 2015
amount = 250

[[scholarships]]
name = "President's Scholarship"
institution = "University of Victoria"
date = 2016
amount = 2000

[[scholarships]]
name = "President's Scholarship"
institution = "University of Victoria"
date = 2016
amount = 2000

[[scholarships]]
name = "President's Scholarship"
institution = "University of Victoria"
date = 2017
amount = 2000

[[scholarships]]
name = "President's Scholarship"
institution = "University of Victoria"
date = 2018
amount = 4000
