knowledge = [
    "C#",
    "ASP.NET",
    ".NET",
    "NUnit",

    "AWS",
    "Terraform",

    "SQL",
    "PostgreSQL",
    "SQL Server",

    "AWS DynamoDB",

    "TypeScript",
    "JavaScript",
    "React",
    "Vue",
    "SolidJS",
    "Preact",
    "KnockoutJS",

    "Docker",
]

defence = false


[[jobs]]
company = "Xplor Recreation"

[[jobs.positions]]
title = "Intermediate Software Developer"
skills = [1, 3, 5]

[[jobs.positions]]
title = "Junior Software Developer"
skills = [1, 3, 4, 6]


[[jobs]]
company = "Helm Operations"

[[jobs.positions]]
title = "Full-stack Developer"
skills = [3, 4, 5]


[[projects]]
title = "Lamport Clock Paper"
skills = [1]

[[projects]]
title = "Apartment Noise Tracker"
skills = [1, 2, 3]

[[projects]]
title = "Rent vs. Buy Calculator"
skills = [1]

[[degrees]]
title = "Bachelor of Science (Honours) (Co-op)"

[[certifications]]
name = "AWS Certified Solutions Architect - Associate"
