knowledge = [
    "C#",
    "ASP.NET",
    ".NET",
    "NUnit",

    "AWS",
    "Terraform",

    "SQL",
    "PosgreSQL",
    "SQL Server",

    "AWS DynamoDB",

    "TypeScript",
    "JavaScript",
    "React",
    "Vue",
    "SolidJS",
    "Preact",
    "KnockoutJS",

    "Docker",
]

defence = false


[[jobs]]
company = "Xplor Recreation"

[[jobs.positions]]
title = "Intermediate Software Developer"
skills = [1, 4]
knowledge = true

[[jobs.positions]]
title = "Junior Software Developer"
skills = [1, 3, 5]
knowledge = true


[[jobs]]
company = "Helm Operations"

[[jobs.positions]]
title = "Full-stack Developer"
skills = [2, 3]
knowledge = true

[[jobs.positions.quotes]]
name = "Peter"


[[jobs]]
company = "Latitude Geographics"


[[jobs]]
company = "UVic Civil Engineering"


[[jobs]]
company = "Demonware"


[[projects]]
title = "Lamport Clock Paper"
knowledge = true

[[projects]]
title = "Apartment Noise Tracker"
skills = [1, 2]
knowledge = true

[[projects]]
title = "Rent vs. Buy Calculator"
skills = [1]
knowledge = true

[[degrees]]
title = "Bachelor of Science (Honours) (Co-op)"

[[certifications]]
name = "AWS Certified Solutions Architect - Associate"
